# Generated by Django 2.2.4 on 2019-11-17 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='DatasetMeta',
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='IecMeta',
        ),
        migrations.DeleteModel(
            name='ImageMeta',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='Software',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
