# Generated by Django 2.2.4 on 2019-11-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_dataset_datasetmeta_environment_equipment_iecmeta_imagemeta_sample_software_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasetId', models.IntegerField()),
                ('fileNames', models.CharField(max_length=255)),
            ],
        ),
    ]
