# Generated by Django 2.2 on 2020-01-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191203_2010'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipment',
            table='equipmentid',
        ),
    ]
