# Generated by Django 2.2 on 2020-01-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200106_1117'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipment',
            table='equipmentId',
        ),
    ]
