# Generated by Django 2.2 on 2020-01-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
